title: Jianfeng Ning
position: Postdoctoral Researcher
description: Jianfeng Ning is a postdoctoral researcher at WIAS working on numerical PDEs, inverse problems, optimization, and machine learning.
url: https://jianfengning.github.io
baseurl: ""
lang: en
timezone: Europe/Berlin
repository: JianfengNing/JianfengNing.github.io

keywords: Jianfeng Ning, numerical PDEs, inverse problems, optimization, machine learning
markdown: kramdown

exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - README copy.md
  - EDITING.md
  - LICENSE
  - CNAME
  - _site
  - blog
  - contact
  - css
  - google_scholar_crawler
  - img
  - js
  - assets/.DS_Store
  - assets/js
  - assets/mpii_files
  - assets/css/nav-ori.css
  - assets/css/nav.css
  - assets/css/pub-ori.css
  - assets/css/pub.css
  - assets/files/.DS_Store
  - assets/files/1-s2.0-S0925400523004458-ga1_lrg.jpg
  - assets/files/JEMS2023.jpg
  - assets/files/JEMS2023_2.jpg
  - assets/files/JEMS2023_Song.pdf
  - assets/files/SSRN-id4328224.pdf
  - assets/files/admi202270196-gra-0001-m.jpg
  - assets/files/flexible.txt
  - assets/files/magnetoionic.txt
  - assets/files/multi.jpg
  - assets/files/multi.pdf
  - assets/files/multi.txt
  - assets/img/.DS_Store
  - assets/img/Group_picture.jpg
  - assets/img/Portada-cc58d654.jpg
  - assets/img/Self.jpg
  - assets/img/autova.png
  - assets/img/avatar.jpg
  - assets/img/eth.jpg
  - assets/img/favicon-dark.png
  - assets/img/favicon.png
  - assets/img/joint.jpg
  - assets/img/lF0ulCNA.jpeg
  - assets/img/spinion.svg
  - assets/img/spinionlogo.png
  - assets/img/university-logo-small-horizontal-white-156eae9527.svg
